config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # GET /about
  get "about", to: "about#index"
  get "pankindex", to: "pankroute#pankindex"
  # root "pankroute#pankindex"
  get "/", to: "pankroute#pankindex", as: :home
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pankroute_controller.rb
class PankrouteController < ApplicationController
  def pankindex
    flash[:notice] = "this is flash notice"
    flash[:alert] = "this is flash alert"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<div class="container">
	<h1>this is about</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <%= render partial: "shared/navigation" %>
    <%= render partial: "shared/flashes"  %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pankroute/pankindex.html.erb
<div class="d-flex align-items-center justify-content-center">
	<h1>pank route here</h1>
	<h1>pank route here</h1>
</div>

app/views/shared/_flashes.html.erb
<% if flash[:notice]  %>
<div class="alert alert-warning" role="alert">
<%= flash[:notice] %>
</div>
<% end %>

<% if flash[:alert  ]  %>
<div class="alert alert-danger" role="alert">
<%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
          <%= link_to "Home", home_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="/about">About</a> %>
          <%= link_to "About", about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%# <a class="nav-link" href="/pankindex">Pankroute</a> %>
          <%= link_to "Pankroute", pankindex_path, class:"nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>